name: main

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: checkout code
        uses: actions/checkout@v2
      - name: install dependencies
        run: pip install flake8
      - name: lint with flake8
        run: flake8 --ignore=E402,E301 -v .
